added unittests to pre-commit hook

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -10,3 +10,10 @@ if [ $? != 0 ]; then
 	printf "${RED}aborting commit due to incomplete formatting.${NOCOLOR}\n"
 	exit 1
 fi
+
+python -m unittest discover
+
+if [ $? != 0 ]; then
+	printf "${RED}aborting commit because unittests failed.${NOCOLOR}\n"
+	exit 1
+fi
